#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/carlos/REPOS/LIL/building-monorepos-on-GitHub-3086076/monorepos/01_03_adding_a_new_project/common/temp/node_modules/.pnpm/esbuild@0.25.6/node_modules/esbuild/bin/node_modules:/Users/carlos/REPOS/LIL/building-monorepos-on-GitHub-3086076/monorepos/01_03_adding_a_new_project/common/temp/node_modules/.pnpm/esbuild@0.25.6/node_modules/esbuild/node_modules:/Users/carlos/REPOS/LIL/building-monorepos-on-GitHub-3086076/monorepos/01_03_adding_a_new_project/common/temp/node_modules/.pnpm/esbuild@0.25.6/node_modules:/Users/carlos/REPOS/LIL/building-monorepos-on-GitHub-3086076/monorepos/01_03_adding_a_new_project/common/temp/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/carlos/REPOS/LIL/building-monorepos-on-GitHub-3086076/monorepos/01_03_adding_a_new_project/common/temp/node_modules/.pnpm/esbuild@0.25.6/node_modules/esbuild/bin/node_modules:/Users/carlos/REPOS/LIL/building-monorepos-on-GitHub-3086076/monorepos/01_03_adding_a_new_project/common/temp/node_modules/.pnpm/esbuild@0.25.6/node_modules/esbuild/node_modules:/Users/carlos/REPOS/LIL/building-monorepos-on-GitHub-3086076/monorepos/01_03_adding_a_new_project/common/temp/node_modules/.pnpm/esbuild@0.25.6/node_modules:/Users/carlos/REPOS/LIL/building-monorepos-on-GitHub-3086076/monorepos/01_03_adding_a_new_project/common/temp/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../bin/esbuild" "$@"
else
  exec node  "$basedir/../../bin/esbuild" "$@"
fi
